name: Deploy S3 via CloudFormation

on:
  push:
    paths:
      - 'infra/cloudformation/s3-bucket.yaml'

jobs:
  deploy-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file infra/cloudformation/s3-bucket.yaml \
            --stack-name devops-github-s3-stack \
            --capabilities CAPABILITY_NAMED_IAM
